
staticDirs:
  - static

services:
  - name: web
    env: python=3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT marc_platform.wsgi:application
    healthCheckPath: /health-check
    httpPort: 8000


static_build_command: "python manage.py collectstatic --noinput"
static_build_path: "staticfiles"
