# Generated by Django 5.0 on 2024-02-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='signature',
        ),
    ]
