# Generated by Django 5.0.2 on 2024-02-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
