# Generated by Django 5.0 on 2024-02-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
    ]
