# Generated by Django 5.0 on 2024-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
        ('ProjectApp', '0002_remove_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='CategoryApp.category'),
        ),
    ]
