# Generated by Django 5.0.2 on 2024-02-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
