# Generated by Django 5.0.2 on 2024-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_remove_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default=1, upload_to='project_photos/'),
            preserve_default=False,
        ),
    ]
