# Generated by Django 5.0.2 on 2024-02-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
